### ISSUE TITLE
[BUG] gh dash crashes when using Github Enterprise 

### ISSUE THREAD

**Issue by omarshaarawi** [dlvhdr/gh-dash#100]
**Describe the bug**
I have my Github host pointed to my company's enterprise instance. When using `gh dash` I receive this message ```2022/04/01 16:16:38 Message: Field 'creator' doesn't exist on type 'CheckSuite', Locations: [{Line:1 Column:651}]
Message: Field 'workflowRun' doesn't exist on type 'CheckSuite', Locations: [{Line:1 Column:666}]```

**To Reproduce**
1. GH config is configured with only the enterprise host
2. `gh dash`

**Expected behavior**
I expected it to work regardless of using Github Enterprise. 
**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS 12.2
 - Shell: Zsh 
 - gh version 2.7.0 (2022-03-30)

**Comment by ryenus** [comment]
Exact same issue here with gh 2.7.0 and gh-dash 3.0.0

> 2022/04/05 10:51:54 
Message: Field 'creator' doesn't exist on type 'CheckSuite', Locations: [{Line:1 Column:651}]
Message: Field 'workflowRun' doesn't exist on type 'CheckSuite', Locations: [{Line:1 Column:666}]

After the crash, I had to run `stty sane` to be able to see what I type.

**Comment by amichne** [comment]
Adding my voice here, faced the same issue when trying to point at a GHE instance.

**Comment by LeonardoFurtado** [comment]
> Exact same issue here with gh 2.7.0 and gh-dash 3.0.0
> 
> > 2022/04/05 10:51:54
> > Message: Field 'creator' doesn't exist on type 'CheckSuite', Locations: [{Line:1 Column:651}]
> > Message: Field 'workflowRun' doesn't exist on type 'CheckSuite', Locations: [{Line:1 Column:666}]
> 
> After the crash, I had to run `stty sane` to be able to see what I type.

@ryenus are you using GH config configured with only the enterprise host too?

**Comment by dlvhdr** [comment]
I don't have a github enterprise account, so bit sure how to solve this. I'd love a contribution from someone who does...

**Comment by LeonardoFurtado** [comment]
> I don't have a github enterprise account, so not sure how to solve this. I'd love a contribution from someone who does...

I'll take a look at this.

**Comment by ryenus** [comment]
> > Exact same issue here with gh 2.7.0 and gh-dash 3.0.0
> > > 2022/04/05 10:51:54
> > > Message: Field 'creator' doesn't exist on type 'CheckSuite', Locations: [{Line:1 Column:651}]
> > > Message: Field 'workflowRun' doesn't exist on type 'CheckSuite', Locations: [{Line:1 Column:666}]
> > 
> > 
> > After the crash, I had to run `stty sane` to be able to see what I type.
> 
> @ryenus are you using GH config configured with only the enterprise host too?

@LeonardoFurtado, no, I work with github.com and more than one GHE hosts, typically I run gh like this to be able to work with certain github host:
* `GH_HOST=<the_gh_host> gh <cmd> ...` 

Currently gh-dash crashes with both GHE 3.0.22 and 3.1.17

**Comment by eisenhowerj** [comment]
gh-dash v3.2.0 is working wonderfully with GHES 3.3.8 and cli/cli v2.14.3
