### ISSUE TITLE
Support commenting

### ISSUE THREAD

**Issue by dlvhdr** [dlvhdr/gh-dash#103]

**Comment by pataquets** [comment]
In a more generalized way, some form of binding keys to commands with token substitutions would be very helpful (eg. bind `R` to command `gh reopen %i`).

**Comment by dlvhdr** [comment]
testing

**Comment by dlvhdr** [comment]
testing 2

**Comment by dlvhdr** [comment]
testing 3

**Comment by dlvhdr** [comment]
testing 4

**Comment by dlvhdr** [comment]
yay!

**Comment by dlvhdr** [comment]
Done in #166
