### ISSUE TITLE
Some suggestions to the documents

### ISSUE THREAD

**Issue by wd** [dlvhdr/gh-dash#108]
I just want to address some issues I met and hope it could help others. 

## The folder that stores the config

According https://pkg.go.dev/os#UserConfigDir, the folder is different in each OS.  it is `~/Library/Application Support/gh-dash` on Mac. 

Don't waste your time struggling with the `~/.config/gh-dash` folder..

## The icons on the UI

You may not see the icons correctly even though you already have installed and used a nerd font. 

That is because some of the icons need to be rendered with the `bold` style. Make sure you have set the bold font correctly.

**Comment by dlvhdr** [comment]
Fixed in #135
