### ISSUE TITLE
UI: option to disable separator line between issues

### ISSUE THREAD

**Issue by pataquets** [dlvhdr/gh-dash#111]
**Is your feature request related to a problem? Please describe.**
Be allowed to disable the line separator between issues/PRs in the main list.

**Describe the solution you'd like**
Add an option in the config file.

**Describe alternatives you've considered**
None.

**Additional context**
Also, coupled with #107, would allow an alternate vertical UI layout.

**Comment by DrakeRubicon** [comment]
I'd love this!

**Comment by grepsuzette** [comment]
If you're referring to those pesky horizontal lines that divide issues or pull requests. Personally, they drive me nuts and I'd love the option to turn them off, as it takes a lot of screen estate.

**Comment by dlvhdr** [comment]
Use the new config option: `theme.ui.table.showSeparator` set to false
