### ISSUE TITLE
Add a 'Load more items' functionality

### ISSUE THREAD

**Issue by pataquets** [dlvhdr/gh-dash#112]
**Is your feature request related to a problem? Please describe.**
With lots of issues and/or PRs, the default displayed items count might come short.

**Describe the solution you'd like**
A key binding which would load more items in the current section.

**Describe alternatives you've considered**
Increasing the loaded items in the config file. But this makes dash slower to load, and eventually you'll hit the limit.

**Comment by dlvhdr** [comment]
This is supported by scrolling to the bottom
