### ISSUE TITLE
Checkout issue/pr

### ISSUE THREAD

**Issue by sean-brydon** [dlvhdr/gh-dash#118]
**Describe the solution you'd like**
Being able to checkout a PR to a new branch with a hotkey would be pretty useful for me. Or the ability to create a new branch witin gh dash 

I understand this may be out of the scope of this project

**Comment by cmygray** [comment]
Good for me either.
But if gh dash is running outside of a git repository, the hotkey would not work.

**Comment by dlvhdr** [comment]
I've just published a proposed solution to #27.
