### ISSUE TITLE
Configuration Override

### ISSUE THREAD

**Issue by michaeltlombardi** [dlvhdr/gh-dash#119]
**Is your feature request related to a problem? Please describe.**
When configuring gh-dash, I realized there are a few different contexts I'd like to be able to set my dashboard for but I'm limited to a single configuration, which means I need to make a compromise to how I view work items.

**Describe the solution you'd like**
Ideally, I would be able to dynamically choose another configuration while already inside gh-dash by pressing a bound key to prompt me for an alternate config file (or presenting a selection of configs stored in the default location).

Secondarily, it would be useful to be able to specify a configuration override as a parameter; for example:

```sh
# pass as full path
gh dash --config /path/to/alt-config.yml
# pass as relative path
gh dash --config ../configs/alt.yml
# pass by name, requiring the `alt.yml` file to be in the same place as `config.yml`
gh dash --config alt
```

**Describe alternatives you've considered**
Workarounds right now for me seem to be:

1. Add more tabs to my views
2. Have more noise in each tab than is desirable
3. Write a shell script to set the config file to my preferences before calling `gh dash`.

**Additional context**
N/A

**Comment by dlvhdr** [comment]
I really like this idea!
