### ISSUE TITLE
[BUG] dash should not lists PRs on archived repositories

### ISSUE THREAD

**Issue by obourgain** [dlvhdr/gh-dash#124]
**Describe the bug**
Dash lists the PRs on archived repos. I can't change those PRs, even not close them. I don't have the rights to unarchive the repos, so I just have zombies PRs in the list.

**To Reproduce**
1. Create a repo
2. Create a PR on it
3. Dash lists the repo
4. Archive the repo
5. Dash stills display the PR

**Expected behavior**
PRs on archived repos should be ignored.

**Desktop (please complete the following information):**
 - OS: OSX

**Comment by dlvhdr** [comment]
Fixed by #124
