### ISSUE TITLE
[BUG] Subscribed Tab Doesn't Show Subscribed Repos/PRs

### ISSUE THREAD

**Issue by PatrickTulskie** [dlvhdr/gh-dash#129]
**Describe the bug**

The "subscribed" tab shows PRs for the gh-dash and cli repos. It doesn't show anything for repos that I am watching.

**To Reproduce**
1. Go to 'subscribed'
2. Observe a bunch of irrelevant entries.

**Expected behavior**

Should show PRs or repos that I am actually subscribed to.

**Screenshots**

NA

**Desktop (please complete the following information):**
 - Any platform

**Comment by dlvhdr** [comment]
Yeah maybe the name is confusing, but it's just an example of a section you can create. Maybe I should look into showing actual repos you're subscribed to

**Comment by PatrickTulskie** [comment]
Ohhh makes sense. I guess this isn't really a bug then. Maybe even just a readme update about that would be cool.

For some reason, my install doesn't have a config in the same location the readme expects it to be though. Should I just put one there and configure that tab that way? Or is there something else I should do?

**Comment by dlvhdr** [comment]
Theres an issue about the config location. If you don't set the XDG variables I put it in a bad location. For now you can just put it under ~/.config/gh-dash/config.yml

**Comment by PatrickTulskie** [comment]
Tried to put a config there and it didn't seem to get picked up so I went searching my drive. Found it in ~/Library/Application Support/gh-dash/config.yml

When I deleted that, it kept recreating the config there so for now I just symlinked it to ~/.config/gh-dash/config.yml and it seems to work now.

Until I opened this bug I didn't realize how configurable this was. Really awesome!

**Comment by dlvhdr** [comment]
Yup that's the issue. If you don't have the XDG env variables set

**Comment by dlvhdr** [comment]
This should be solved now with the latest version.
