### ISSUE TITLE
[BUG] "Resource protected by organization SAML enforcement." when used on independent repository

### ISSUE THREAD

**Issue by ericcornelissen** [dlvhdr/gh-dash#140]
**Describe the bug**
When I try to use gh-dash on a repository owned by my personal account I'm getting an error related to SAML, while SAML is only required for repositories from one of the GitHub organizations that I'm a member of.

**To Reproduce**
1. Be part of an organization that enforces SAML
2. Authenticate the GitHub CLI outside the enforced SAML
3. Navigate to a local clone of a repository from your personal GitHub account
4. Run `gh dash` (after having installed it, of course)
5. See error
   ```
   YYYY/MM/DD HH:mm:SS Message: Resource protected by organization SAML enforcement. You must grant your OAuth token access to this organization., Locations: [{Line:1 Column:103}]
   ```

**Expected behavior**
Using gh-dash on a repository without SAML requirements should work, even if the user is part of an organization that has SAML requirements.

<details>
<summary><b>Screenshots</b></summary>

![Screenshot from 2022-06-13 23-53-21](https://user-images.githubusercontent.com/3742559/173451912-50fcdd95-e3a8-4d9f-a166-18b66c954a6f.png)

</details>

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.4 LTS (64 bit)

**Comment by dlvhdr** [comment]
I also have repos that are protected with SAML and everything works.
Wdym by this...?
| Authenticate the GitHub CLI outside the enforced SAML

**Comment by ericcornelissen** [comment]
> Wdym by this...?
> 
> > Authenticate the GitHub CLI outside the enforced SAML

Running

```sh
gh auth login
```

Selecting the web authentication mechanism:

![select authentication mechanism](https://user-images.githubusercontent.com/3742559/177218496-f2b9b9c9-6504-413c-8d83-0fc829266eb8.png)


and when presented with:

![authentication preview](https://user-images.githubusercontent.com/3742559/177218255-5a29633e-58ed-486a-bc8a-3d8850eecfe5.png)

Not "Authorize"-ing the (SAML) organization (instead clicking "Continue")

**Comment by dlvhdr** [comment]
I removed some `log.Fatal`s from the code, so this shouldn't crash the app anymore.

**Comment by ericcornelissen** [comment]
Just tested [v3.6.0](https://github.com/dlvhdr/gh-dash/releases/tag/v3.6.0) and can confirm this fixed the problem, thanks! :+1:
