### ISSUE TITLE
The custom command worked replacing `/bin/sh` by `sh` there [modelUtils](https://github.com/dlvhdr/gh-dash/blob/6dd931d88eb20774dfa349ddd954fd0638e2055c/ui/modelUtils.go#L91).

### ISSUE THREAD

**Issue by torranalexander** [dlvhdr/gh-dash#144]
The custom command worked replacing `/bin/sh` by `sh` there [modelUtils](https://github.com/dlvhdr/gh-dash/blob/6dd931d88eb20774dfa349ddd954fd0638e2055c/ui/modelUtils.go#L91).

_Originally posted by @gcoutable in https://github.com/dlvhdr/gh-dash/issues/143#issuecomment-1175361515_

**Comment by dlvhdr** [comment]
Should be fixed
