### ISSUE TITLE
Question: how do I navigate to the Issues?

### ISSUE THREAD

**Issue by shmup** [dlvhdr/gh-dash#152]
I see an indicator this is possible in the top right, and I do want to verify I'm rendering it correctly. Something does feel off with the text. But that's besides the point. How do I get there, is the hotkey mentioned in `?`

![image](https://user-images.githubusercontent.com/118710/181666532-9dba63ce-bfc8-49c0-954c-a0e07e7efd62.png)

Cheers! Lovely extension

**Comment by dlvhdr** [comment]
Hey! You press <kbd>s</kbd>

**Comment by shmup** [comment]
@dlvhdr thank you! Regarding the font choice, and requiring the user to configure their terminal with a very specific font, I'm wondering if we want two modes.

One that uses all your favorite fun unicodes. And the other that would render in the other 99.9% of cases.

I'll be hard pressed to give up https://fsd.it/shop/fonts/pragmatapro/ :innocent: 

On a quick glance, it doesn't even appear there is really much being leveraged with the specific font choice, I only see a few goofs:

![image](https://user-images.githubusercontent.com/118710/181783625-ba2e2316-6dd8-4088-abf0-846d22e68864.png)

**Comment by dlvhdr** [comment]
You can patch any existing font ![image](https://user-images.githubusercontent.com/6196971/181808768-1dca4b0f-82a0-438e-9d08-9313face03cb.png)

See the https://www.nerdfonts.com if you want.

**Comment by shmup** [comment]
Appreciate the reply. Patching is not an option for me right now, but I totally get that people love their unicodes. I decided to run a fork for now, and see if it becomes too painful in the future to manage :P 

Went a bit more standard w/ some of the unicode, though a few were odd choices (on my part). Oh well.

https://github.com/shmup/gh-dash/pull/1

**Comment by shmup** [comment]
(Though, I suppose if anything I should have set up label definitions in the config.yml, heh)
