### ISSUE TITLE
[BUG] Dash does not open on NixOS

### ISSUE THREAD

**Issue by minsk-dev** [dlvhdr/gh-dash#154]
**Describe the bug**
You can't open `gh-dash` on NixOS. This occurs because of how NixOS manages linkers. The only way I know to fix this bug is by creating a nix package and running it. I will do this later, so you can assign this bug to me. After I do the package, I will add a how-to installation section for nixos users.

**To Reproduce**
1. Use NixOS
2. Install `gh-dash`
3. Run `gh dash`

**Expected behavior**
The application should open

**Logs**

Trying to open `dash` gives you this error:

```
failed to run extension: fork/exec /home/alex/.local/share/gh/extensions/gh-dash/gh-dash: no such file or directory
```

**Desktop (please complete the following information):**
 - OS: NixOS 22.05

**Comment by amesgen** [comment]
I recently packaged gh-dash in nixpkgs (https://github.com/NixOS/nixpkgs/pull/183140), it is already in nixpkgs-unstable. In there, it is available as `gh-dash`.

If you use home-manager, you can also make `gh` aware of it, such that e.g. `gh dash` works: https://nix-community.github.io/home-manager/options.html#opt-programs.gh.extensions (https://github.com/nix-community/home-manager/pull/3119)

**Comment by minsk-dev** [comment]
@amesgen Thanks for your help :)
