### ISSUE TITLE
Allow reponame length configuration

### ISSUE THREAD

**Issue by hans-d** [dlvhdr/gh-dash#155]
**Is your feature request related to a problem? Please describe.**
Repo names are now shortened to a fixed number of chars. Would like some control for this.

**Describe the solution you'd like**
config.yaml option to specify max chars

**Additional context**
sometimes repo names are not very short

**Comment by chrheg** [comment]
This would be a really great feature to have.

**Comment by dlvhdr** [comment]
Done in #178
