### ISSUE TITLE
Differentiate Draft PRs

### ISSUE THREAD

**Issue by molawson** [dlvhdr/gh-dash#157]
**Is your feature request related to a problem? Please describe.**
There's no way in the gh-dash UI to tell that a PR is a draft.

**Describe the solution you'd like**
It would be super helpful if the PR icon in the table view for a draft PR could be a different color (gray?) to differentiate it from open PRs, and for the pill in the sidebar for the PR state to use that same color and say "Draft".

**Describe alternatives you've considered**
None come to mind other than leaving it as-is 😄 

**Additional context**
I'm happy to take a crack at implementing the feature if it seems useful!

**Comment by drupol** [comment]
Just FYI, if you want to disable `draft`, just add `draft:false` in the filter.
