### ISSUE TITLE
[BUG] Bad Gateway Body

### ISSUE THREAD

**Issue by masukomi** [dlvhdr/gh-dash#159]
**Describe the bug**
quits with an unexpected Bad Gateway body message from github while "Fetching Pull Requests..."
```
2022/08/19 10:39:02 non-200 OK status code: 502 Bad Gateway body: 
{
   "data": null,
   "errors":[
      {
         "message":"Something went wrong while executing your query.
                   This may be the result of a timeout, or it could
                   be a GitHub bug. Please include `E03D:7A79:100FF87:1F75007:62FFA07B`
                   when reporting this issue."
      }
   ]
}
```
( i took the liberty of formatting the response JSON above so it could be read. )

It's not obvious to me if this is a GH problem or a result of the quantity of info it'd need to display for me combined with whatever query you're using.  It's repeatable (days apart) so I'm inclined to think it's a byproduct of the request causing an overly long processing on their end, which causes a timeout. 

**To Reproduce**

1. be me (sorry) or someone with a LOT of PRs and notifications and whatever else you're pulling. 
2. run `gh dash`
3. wait

**Expected behavior**
not crashing.

**Desktop (please complete the following information):**
 - OS: macOS 12.5.1

**Comment by dlvhdr** [comment]
Are you using a limit of some kind? You can add a limit
per section, maybe that will help?

**Comment by masukomi** [comment]
sorry about the delayed response. No, i was not using limits. Yes, adding limits solved it, but that introduces the problem of not knowing what, or how much, I'm missing.

**Comment by dlvhdr** [comment]
Yeah @masukomi I need to add support for pagination
