### ISSUE TITLE
Add JSON Schema for config

### ISSUE THREAD

**Issue by michaeltlombardi** [dlvhdr/gh-dash#162]
**Is your feature request related to a problem? Please describe.**

When I'm editing the config, I need to keep the docs open and constantly refer back and forth while I make changes, both to see what keys are available and how to write a valid value.

**Describe the solution you'd like**

With a JSON Schema for the config file, I could tell my editor what schema to use and then get auto-completion, validation, and documentation for the settings in the same context, reducing my cognitive load and making it easier to author and update my configuration(s).

**Describe alternatives you've considered**

I could write my own standalone schema file and keep it locally, but that wouldn't benefit the community and would likely drift from accuracy with each release.

**Additional context**

N/A

**Comment by andrewg-xyz** [comment]
Discovered the Schema exists: https://dlvhdr.github.io/gh-dash/configuration/gh-dash/schema.json while browsing docs: https://dlvhdr.github.io/gh-dash/configuration/gh-dash/
