### ISSUE TITLE
Extending standard GH filters with more pre-/post- filter request logic

### ISSUE THREAD

**Issue by kliakhovskii-brex** [dlvhdr/gh-dash#182]
**Is your feature request related to a problem? Please describe.**
I'd really love to see an ability to filter issues that I have approved. That seems that for some reason GH still [does not have this filter in the status related](https://docs.github.com/en/search-github/searching-on-github/searching-issues-and-pull-requests#search-by-pull-request-review-status-and-reviewer). But the gh-dash extension shows the data on approved state from yourself in the PR details, so it's technically possible to separate `reviewed-by:@me` results into more subgroups (e.g. `approved` / `commented` / `rejected`).

Currently, my need is to be able to identify the PRs that were reviewed by me, but not approved yet.

Additionally that can enable relative dates for the date-related search, or `lastDay()` query for [these](https://docs.github.com/en/search-github/getting-started-with-searching-on-github/understanding-the-search-syntax#query-for-dates). Or even filters based on where the issues been reviewed & relative dates on those.

**Describe the solution you'd like**
For `pre-` filters: Transform the query on the fly before executing against GH cli.
For `post-` filters: Transform the response from a query to filter into more sub-categories.

**Describe alternatives you've considered**
Doesn't seem possible with `gh dash` now, that's somewhat possible with just direct `gh cli` calls as just requires extra scripting.

**Additional context**
Here is the case I want to filter out of `review-by:@me`

> I approved it, but overall the PR is still not fully `review:approved` state as not all codeowners have approved

![Screen Shot 2022-10-05 at 2 41 15 PM](https://user-images.githubusercontent.com/89865360/194169340-7b78126f-bfd2-4e1e-9a45-498e03b85511.png)

**Comment by dlvhdr** [comment]
Yeah seems like github doesn't support this yet... Adding a pre/post filters to the request will probably work but won't be clean when too many results return by none match the exact filter you want. It might be the case that the PRs you want will be shown only on the next page...

**Comment by kliakhovskii-brex** [comment]
> Yeah seems like github doesn't support this yet... Adding a pre/post filters to the request will probably work but won't be clean when too many results return but none match the exact filter you want. It might be the case that the PRs you want will be shown only on the next page...

yup, client-side filtering has this problem and it's not ideal. I wished GH supported those filters or relative dates out of the box, but unfortunately we do not have control of that :(

**Comment by dlvhdr** [comment]
yeah bummer...
thanks for the issue.

**Comment by kliakhovskii-brex** [comment]
> yeah bummer...
thanks for the issue.

Is that smth you'd be willing to support as a part of `gh dash` tooling?
