### ISSUE TITLE
Feature Request: Automatic refresh

### ISSUE THREAD

**Issue by MichaelDepner** [dlvhdr/gh-dash#193]
**Is your feature request related to a problem? Please describe.**
I often have gh-dash open in a terminal on a secondary monitor to keep track of incoming PRs. This doesn't work very well currently, since I have to manually switch over to the window and press `r` to refresh.

**Describe the solution you'd like**
I'd love a setting in the config file that makes the currently active tab auto refresh every x seconds: 
```
defaults:
  autoRefreshInterval: 60
```

**Describe alternatives you've considered**
Might also consider automatically refreshing on tab change if it's been longer than `auto_refresh_interval` since you last visited it.

**Comment by dlvhdr** [comment]
Yeah I like this a lot!

**Comment by dlvhdr** [comment]
This is done!
Check out the `refetchIntervalMinutes` config option.
