### ISSUE TITLE
Add version information to the dash executable

### ISSUE THREAD

**Issue by sdwheeler** [dlvhdr/gh-dash#207]
As a user, I want to know what version of a program I have installed.

**Describe the solution you'd like**
Add a `-v, --version` option to the command line. Display the version in the help pane of the UI.

**Comment by amesgen** [comment]
Note that despite version 3.6.0 being released, the flag still says 3.5.1:

https://github.com/dlvhdr/gh-dash/blob/0b1a3eaa5291f046b32d9e6a34c4e442c5f683d0/cmd/root.go#L26

Maybe allow to pass this in via a linker flag (`-X`) such that the source does not have to be updated on every release?

**Comment by dlvhdr** [comment]
Nice. Didnt know about that. Ill read on these flags

**Comment by amesgen** [comment]
Sorry if that was a bit cryptic, I am talking about e.g. https://www.digitalocean.com/community/tutorials/using-ldflags-to-set-version-information-for-go-applications or https://pkg.go.dev/cmd/link

**Comment by amesgen** [comment]
Thanks, this seems to be fixed now :heart:
