### ISSUE TITLE
[BUG] Fatals when using Github Enterprise

### ISSUE THREAD

**Issue by roginfarrer** [dlvhdr/gh-dash#213]
**Describe the bug**

When trying to use my Github Enterprise host, gh dash fatals with this error:

`non-200 OK status code: 401 Unauthorized body: "Invalid IAP credentials: empty token"`

But I believed I'm logged in, and I can't figure out what credentials it's missing.

* `gh auth status` shows I'm logged in to my Enterprise host using the https protocol.
* I've also set a personal access code to `GH_ENTERPRISE_TOKEN`

**To Reproduce**

1. Login to custom host using `gh auth login --hostname git.company.com`
2. Execute `GH_HOST=git.company.com gh dash`
3. Opens and immediately errors `non-200 OK status code: 401 Unauthorized body: "Invalid IAP credentials: empty token"`

**Expected behavior**

GH Dash should launch with my Github Enterprise data

**Desktop (please complete the following information):**
 - OS: Mac

**Comment by dlvhdr** [comment]
Sorry, I don't have a GH enterprise account, this can't really support this.
Unless, someone who does have can debug this.
