### ISSUE TITLE
[BUG] Icons not displayed

### ISSUE THREAD

**Issue by hubwriter** [dlvhdr/gh-dash#220]
**Describe the bug**
The icons are replaced by "?":

<img width="1057" alt="image" src="https://user-images.githubusercontent.com/54933897/212646308-b8253d04-f632-4f6f-b69c-fc0191ffb787.png">

**Desktop (please complete the following information):**
 - OS: MacOS

**Comment by dlvhdr** [comment]
Hi, did you try installing a Nerd Font? See the README

**Comment by hubwriter** [comment]
Ah, yes. Thanks. Installing the Fira Code nerd font fixed this. 👍

**Comment by ssbarnea** [comment]
I hate that this cool tool forces us to use nerd fonts. This should have being optional as I do not want to change the fonts.

**Comment by dlvhdr** [comment]
You can also use a terminal with fallback fonts like wezterm
