### ISSUE TITLE
How can I buy you a coffee (or tea or beer)?

### ISSUE THREAD

**Issue by sethlivingston** [dlvhdr/gh-dash#247]
This is a fantastic application. How can I thank you?

**Comment by dlvhdr** [comment]
Thank you, this warms my heart ❤️ 
I might set up a github sponsors, does that work for one time coffee donations?

**Comment by sethlivingston** [comment]
I believe it does. You deserve it!

**Comment by dlvhdr** [comment]
Hey @sethlivingston I've just joined GitHub sponsors, really appreciate the push and support! https://github.com/sponsors/dlvhdr

**Comment by dlvhdr** [comment]
Thank you! ❤️
