### ISSUE TITLE
[BUG] RepoPath wildcard matching does not work for built-in commands

### ISSUE THREAD

**Issue by robdimsdale** [dlvhdr/gh-dash#250]
**Describe the bug**

Built-in commands (like "checkout") do not work with the wildcard matching introduced in #150 - this feature was only implemented for custom commands.

**To Reproduce**

1. Create a wild card `repoPath`
2. Try to checkout a PR locally with `C` that should match the `repoPath` wildcard
3. See error: `Local path to repo not specified, set one in your config.yml under repoPaths`

**Expected behavior**

I would expect that setting wildcard matches under `repoPaths` should work for built-in commands as well as for custom commands.

**Desktop (please complete the following information):**
 - OS: [e.g. Mac]

** Suggested solution**

I think we can extract [`ui.getRepoLocalPath`](https://github.com/dlvhdr/gh-dash/blob/50cd7818576a43f50d7523d20abe0ddff62fb4b8/ui/modelUtils.go#L64) into a separate package and then reference it from both the custom commands and the built-in commands.

We have to extract it to a separate package in order to avoid an import loop between the `ui` and the `prsection` package.

**Comment by robdimsdale** [comment]
This is a really easy fix, and I'm happy to submit a PR, but I want to ensure that you agree this is a bug and we are aligned on the refactor to fix it.

**Comment by dlvhdr** [comment]
Sounds like a bug to me! I haven't used custom commands for a long time so it makes sense I missed this
