### ISSUE TITLE
Support linux-arm

### ISSUE THREAD

**Issue by kronn** [dlvhdr/gh-dash#266]
**Is your feature request related to a problem? Please describe.**
I wanted to install the extension on my chromebook, which has an arm7l-cpu.

**Describe the solution you'd like**
linux-arm is supported

**Describe alternatives you've considered**
none

**Additional context**
I suspect that supporting a new architecture can be a lot of work (can also be
easy, I know). Since I do not know how important this extension is too me, I
cannot put extra pressure. I think it would be neat to have it run on arm in
linux.

**Comment by wwsean08** [comment]
it technically is on arm on linux, just 64 bit arm right now as you can see from the latest release.  It's a relatively simple change to make, though I still can't be sure that your computer will pick it up as go either has arm64 (for 64 bit arm CPUs) or arm6 for other arm CPUs, so while I imagine it would get picked up by the `gh` command and installed, not positive. I'll open a PR shortly.

**Comment by kronn** [comment]
Thank you this. 

(Written from inside gh-dash on my arm-chromebook)

I can now work better from the CLI.
