### ISSUE TITLE
Support android-arm64

### ISSUE THREAD

**Issue by exatonix** [dlvhdr/gh-dash#341]
not support by arm64 says in termux (Redmi Note 10S A13 Tiramisu Lineage OS 18 Based Custom Crdroid 9.2 ROM (Root/Unroot)

**Comment by exatonix** [comment]
not support by arm64 says in termux (Redmi Note 10S A13 Tiramisu Lineage OS 18 Based Custom Crdroid 9.2 ROM (Root/Unroot)

**Comment by HyperAfnan** [comment]
Duplicate of #304
