### ISSUE TITLE
[BUG] Cannot show PRs - too many graphql nodes

### ISSUE THREAD

**Issue by robdimsdale** [dlvhdr/gh-dash#367]
**Describe the bug**

After updating GH Dash from `v3.13.1` to `v3.14.0` (latest), I can no longer view any of my PRs. I get the following message, and then GH Dash crashes:

```
2024/05/23 08:16:06 ERRO Task finished with error id="fetching_prs_5_2024-05-23 08:16:06.337523 -0700 PDT m=+0.016650001" err="GraphQL: This query requests up to 506,650 possible nodes which exceeds the maximum limit of 500,000."
```

I observed this even with a minimal config that looks like the following:

```
prSections:
- title: RDZ-website
  filters: repo:robdimsdale/dimsdale-website`
issueSections: {}
```

**To Reproduce**

I think this might be hard for someone else to reproduce as it's probably environmental - I am a contributor on hundreds of repositories with hundreds of PRs on each repository, and each PR might have 1-100 comments.

**Expected behavior**

I expected to be able to view a list of my PRs.

**Suggested Fix**

I think we may need to make the recent [display review threads feature](https://github.com/dlvhdr/gh-dash/commit/bf3764ced0f35251bc315e634366ea4582313e90) optional. Disabling that feature would allow me to continue using the latest version of `gh-dash`.

**Screenshots**

Can provide if it's helpful beyond the error message above

**Desktop (please complete the following information):**

Can provide if it's helpful beyond the error message above

**Comment by dlvhdr** [comment]
Hey @robdimsdale :)
I can always add a `commentsLimit` field to the config, but let's verify the problem first.
I couldn't reproduce with the provided config, probably because I don't have the right permissions. I did see 2 prs returned.

Can you also try to limit the number of PRs returned with the global settings?
```yaml
defaults:
  prsLimit: 20
  issuesLimit: 20
```

**Comment by robdimsdale** [comment]
I tried limiting the number of PRs but that didn't fix it. However, it looks like the latest release (`v4.0.0`) **does fix** this for me.

I suspect I needed [this commit](https://github.com/dlvhdr/gh-dash/commit/e41171fb17ccba98622ad87a2ec4114d5bcbb965).

I'll close this now. Sorry for the noise :)
