### ISSUE TITLE
Add a filter to hide old PRs/issues

### ISSUE THREAD

**Issue by spencewenski** [dlvhdr/gh-dash#374]
**Is your feature request related to a problem? Please describe.**
At my company, there are a lot of PRs that have been open for a long time without updates, introducing a lot of visual clutter to the dashboard.

**Describe the solution you'd like**
I would love to be able to filter out PRs that have not been updated in X days.

**Describe alternatives you've considered**
GitHub provides an `updated` filter, which accepts a time range, e.g. `>=2024-04-28` would show only the items updated since 2024-04-28. However, this time range is not dynamic, so I can't provide a number of days here and instead need to provide a specific date.

**Additional context**

**Comment by polds** [comment]
lol, I opened this feature immediately after you https://github.com/dlvhdr/gh-dash/issues/375#issue-2321687879
