### ISSUE TITLE
Config location

### ISSUE THREAD

**Issue by muesli** [dlvhdr/gh-dash#5]
Nice work on this project, loving it! A little gripe I have is the config path however: `~/.config/prs` feels a bit generic.

`go-app-paths` could come in handy here: https://github.com/muesli/go-app-paths
This sticks to the XDG specifications and return "native" paths on Windows/Mac as well. Let me know if I can help with this!

Keep up the great work!

**Comment by KyleKing** [comment]
I second this. Having the configuration file in `~/` makes it easier to sync with other dot files

Also, I really like how [`lazygit` uses a configuration file](https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#user-config). The default file is empty, so you can immediately start using the TUI. Then pressing `e` will open the config file in the default git editor)

**Comment by dlvhdr** [comment]
@muesli, I would love to use your package, but I'm a mac user and I like my configs to sit in ~/.config/app
A lot of the apps I use respect the `XDG_CONFIG_HOME=$HOME/.config` env variable.
Maybe this should be added to your repo?

**Comment by michaeltlombardi** [comment]
Relatedly, it might be worth dropping a note in the readme to [`os.UserConfigDir`](https://pkg.go.dev/os#UserConfigDir) - a coworker was having trouble getting their config to work on Windows and I only knew where to look because of this issue mentioning the method. I'm happy to put up a PR for annotating the config location a little more clearly if desired while discussion on whether to change the path-determining continues.

**Comment by edgarrmondragon** [comment]
@michaeltlombardi +1 for that. According to the readme, I should've been able to find the config file in `~/.config/gh-dash/` but it was actually in `~/Library/Application\ Support/gh-dash/config.yml` for macos.

**Comment by dlvhdr** [comment]
Fixed in #135

**Comment by Gustav-Eikaas** [comment]
Sorry for commenting on this closed issue, but after reading all these comments im still unsure where to place my config.yml on windows. 

is it under %user%/AppData\Local\GitHub CLI\extensions\gh-dash?
I have tried different solutions but cant make it work
