### ISSUE TITLE
Allow configuring date format

### ISSUE THREAD

**Issue by schpet** [dlvhdr/gh-dash#67]
**Is your feature request related to a problem? Please describe.**

when i look at a PR from December it is displayed as "1y ago"

**Describe the solution you'd like**

i'd like to be able to configure a custom date format in the config.toml file

**Describe alternatives you've considered**

using iso8601 dates instead of relative dates across the board, also seems reasonable, but i imagine some folks like relative timestamps

**Additional context**

![image](https://user-images.githubusercontent.com/921605/149041214-62325361-150b-4723-ab7b-324ef84eb375.png)

**Comment by miniscruff** [comment]
I was looking through the issues and was wondering if this was still a requested feature. I know its quite old but seemed fairly straight forward and could be an easy one to start with. 

My initial idea was to add a Format config as part of the layout option. The idea being the special value "RELATIVE", being the default, would maintain the existing functionality. While any other value would be considered a Go time format.

```go
type TimeColumnConfig struct {
  ColumnConfig `yaml:",inline"`
  // Format specifies how times are formatted, the special value of "RELATIVE" will
  // use a relative to now output, such as "3m ago" otherwise a Go time format is expected.
  Format string `yaml:"format"`
}

type PrsLayoutConfig struct {
  UpdatedAt    TimeColumnConfig `yaml:"updatedAt,omitempty"`
  # ... others cut
}
```

^ would probably also work for issues and other "times" like maybe created at if that is somewhere.

I am not sure if layout is the best place for this as it seems this is only used in the creation of the table itself. I also considered the `PrsSectionConfig` but adding an "updated at time format" seemed out of place.

I wasn't quite able to get this value in the rendering part as there doesn't seem to be a direct relationship between the pull render function ( ui/components/pr/pr.go PullRequest.renderUpdateAt ) and the specific layout we are rendering. The best I could see was to use `pr.Ctx.Config.Defaults.Layout.Prs` which doesn't seem right.
