### ISSUE TITLE
[BUG]  failed to run extension

### ISSUE THREAD

**Issue by amircp** [dlvhdr/gh-dash#75]
**Describe the bug**

After running for first time `gh prs` the command line shows the following message:

```
➜ gh prs
failed to run extension: fork/exec /Users/macbookpro/.local/share/gh/extensions/gh-prs/gh-prs: no such file or directory%
(base)
```
as a result i cannot execute the prs extension.

**To Reproduce**
1. Install prs extension `gh extension install dlvhdr/gh-prs`
2. run gh prs
3. voila error message.

**Expected behavior**
Must open the prs extension.

**Screenshots**
![Captura de Pantalla 2022-01-25 a la(s) 8 36 44](https://user-images.githubusercontent.com/495849/150998338-eee106fa-856f-4f9a-9ac4-76a48c9afb45.png)

**Desktop (please complete the following information):**
 - OS: macoS Big Sur, v11.6

**Additional information and quick fix**
Checking the folder where the gh-prs extension was installed i realized there's a go script file 
"gh-prs.go" seems it wasn't compiled.

the quick fix was to run` go build -o gh-prs`
After running the compiler build i got my gh-prs running.

As an additional note,  after realizing it was a go script, installed with brew the go lang interpreter and removed and re-installed the extension... and the same problem continued happening.

**Comment by dlvhdr** [comment]
Closing as stale
